# Generated by Django 5.0.4 on 2024-04-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_project_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
